### ISSUE TITLE
Unclear error when peeking zero bits

### ISSUE THREAD

**Issue by wetheredge** [nickbabcock/bitter#24]
In working on some older code using your library, I accidentally called `BigEndianReader::read_bits(0)` and got this panic:

> thread '...' panicked at 'attempt to shift right with overflow', .../bitter-0.6.0/src/lib.rs:793:9

It wasn't immediately obvious what caused this without reading the source and checking the docs. Perhaps `*EndianReader::peek` or `read_bits` could use another `debug_assert!` to make the error message clearer?

If you'd like, I can submit a PR.

**Comment by nickbabcock** [comment]
Yeah, absolutely a PR would be nice.
