### ISSUE TITLE
Faster way to read unaligned bytes

### ISSUE THREAD

**Issue by LaihoE** [nickbabcock/bitter#30]
Currently "unaligned" bytes are read with "read and refill", but I think we could do quite a bit better.

The idea is to take the buffer as is and bitshift the all bytes in one loop with SIMD.

The below produces nice auto-vectorized code that is >10x faster on bigger reads.

For example here we are "4 bits into a byte":
```Rust
pub fn read_n_bytes(&mut self, n: usize, input: &[u8], out: &mut [u8]) {
    let left_mask = 0b00001111;
    let right_mask = 0b11110000;
    for i in 0..n {
        let left_part = input[i] & left_mask;
        let right_part = input[i + 1] & right_mask;
        out[i] = left_part | right_part;
    }
}
```
I gave it a shot myself but couldn't quite get the state correct after this operation.

**Comment by nickbabcock** [comment]
What an excellent idea, especially if the compiler auto vectorizes.

**Comment by nickbabcock** [comment]
I've opened #31 which I believe is what you're aiming for, right? I haven't tested anything or verified that it auto-vectorized so there's still some work left.
