### ISSUE TITLE
Big endian support

### ISSUE THREAD

**Issue by Herschel** [nickbabcock/bitter#8]
Thank you for the crate! Supporting big-endian bitstreams would be a useful feature.

**Comment by nickbabcock** [comment]
Agreed, I assume ergonomics like byteorder's is suitable.

**Comment by nickbabcock** [comment]
Just tidying up the implementation and fleshing out the rest of the docs and tests. Should be released in a couple days.

**Comment by nickbabcock** [comment]
This has been included in the v0.5 release along with other improvements.
